name: Deploy Next.js to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js project
        run: |
          npm run build

      - name: Upload to cPanel via FTP
        uses: sebastianpopp/ftp-action@v1.1.0
        with:
          host: ${{ secrets.CPANEL_HOST }}
          user: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          localDir: out/
          remoteDir: /
